apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-egressgateway
  labels:
    app.kubernetes.io/part-of: istio
spec:
  releaseName: istio-egressgateway
  dependsOn:
    - name: istio-base
    - name: istiod
  chart:
    spec:
#      version: 1.19.7
      version: ${chart_version}
      chart: gateway
      sourceRef:
        kind: HelmRepository
        name: istio
  interval: 60m
  values:
    labels:
      app: istio-egressgateway
      istio: egressgateway
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 80
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
    service:
      type: ClusterIP