apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: istio-version
  namespace: tanzu-continuousdelivery-resources
spec:
  postBuild:
    substitute:
      chart_version: 1.19.7
  prune: true
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: tmc-flux-poc
    namespace: tanzu-continuousdelivery-resources
