apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- ./base
- ./cluster-rbac
- ./crds

patches:
- path: overlays/argocd-server-service.yaml
  target:
    kind: Service
    labelSelector: "app.kubernetes.io/name=argocd-server"