apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault
resources:
- ./namespace.yaml
- ./repository.yaml
- ./vault.yaml

configMapGenerator:
- name: vault-dev-config
  files:
    - values.yaml=config/dev-values.yaml
configurations:
  - kustomizeconfig.yaml