apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  labels:
    app.kubernetes.io/part-of: vault
spec:
  releaseName: vault
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      version: ${chart_version}
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: vault
  valuesFrom:
  - kind: ConfigMap
    name: vault-dev-config
  interval: 60m