apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: argocd
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./addons/base/argocd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-addons-repo
    namespace: tanzu-continuousdelivery-resources