apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: vault
  namespace: tanzu-continuousdelivery-resources
spec:
  postBuild:
    substitute:
      chart_version: 0.27.0
  interval: 1m0s
  path: ./addons/base/vault
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-addons-repo
    namespace: tanzu-continuousdelivery-resources